[phases.setup]
nixPkgs = ["python39", "postgresql_16", "gcc"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "python databaseChecker.py"
